gateway:
  ros__parameters:
    bin_selection: 3 # 5 for FSLICE, 3 for DSLICE
wall_detection:
  ros__parameters:
    mode: 1 # 0: FSLICE, 1: DSLICE
    drone: 2 # 0: none, 1: buzzer, 2: flying
logging: "warn"
