gateway:
  ros__parameters:
    window_type: 2 # flattop
    bin_selection: 5 # one sweep = one buffer
wall_detection:
  ros__parameters:
    mode: 0 # 0: FSLICE, 1: DSLICE
    drone: 2 # 0: none, 1: buzzer, 2: flying
launch:
  ros__parameters:
    log_level: "warn"
    bag_record_root: "datasets/2021_01_27_demo/test"
